### ISSUE TITLE
A Bug in changing the `field_range`

### ISSUE THREAD

**Issue by lsyxiaopang** [jposada202020/CircuitPython_qmc5883l#1]
Hi, I recently use your package for one of my project, it is very convenient to use.  
However, I've found that when I change the `field_range`, the resolution doesn't change.

I've noticed that in your package, there is an error

```python
    @field_range.setter
    def field_range(self, field_range: int) -> NoReturn:

        if range == 1:
            self.resolution = 3000
        else:
            self.resolution = 12000

        self._field_range = field_range
```

You may mistakenly check `range == 1` ranther than `field_range==1`

**Comment by lsyxiaopang** [comment]
Also, I hope you can add the unit (Gs) in the doc

**Comment by jposada202020** [comment]
@lsyxiaopang Ill take a look of your comment.
A question, could you clarify what do you mean by the Gs unit?

**Comment by lsyxiaopang** [comment]
> @lsyxiaopang Ill take a look of your comment. A question, could you clarify what do you mean by the Gs unit?

I think you should use this in your example:
`print("x:{}Gs,y:{}Gs,z:{}Gs".format(mag_x, mag_y, mag_z))`

**Comment by lsyxiaopang** [comment]
Also, I've found that this library cannot handle negative data properly

Maybe you could try this?

```python
    def _get_real_value(self,roughLSB):
        data=roughLSB
        # print(bin(data))
        if((roughLSB>>15)>0):#negative
            # print("Negative")
            data=-(int(~data&0xffff)+1)
            # print(data)
        return data/self.resolution
```

And in your `magnetic`,use
```python
return (
                self._get_real_value(values[0]),
                self._get_real_value(values[2]),
                self._get_real_value(values[4]),
            )
```

**Comment by jposada202020** [comment]
Thank you 👍🏼

**Comment by jposada202020** [comment]
@lsyxiaopang could you take a look at V 0.1.1. thanks!
